[package]
name = "starla-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Measurement scheduling and execution for the Starla RIPE Atlas software probe"
repository.workspace = true
readme = "README.md"

[dependencies]
starla-common = { path = "../starla-common", version = "0.6.0" }
starla-measurements = { path = "../starla-measurements", version = "0.6.0" }
starla-results = { path = "../starla-results", version = "0.6.0" }
starla-metrics = { path = "../starla-metrics", version = "0.6.0" }
tokio = { workspace = true }
tokio-util = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
