//! Packaging metadata derived from the translation catalogues.
//!
//! The entry's user-visible fields come from the same Fluent catalogues
//! as the tray menu, so a translator who localizes the app also
//! localizes how it appears in the application launcher — no separate
//! translation format, and no chance of the two drifting apart.
//!
//! `packaging/starla-tray.desktop` is the committed output of
//! [`desktop_entry`]; the tests below keep it, and the macOS bundle's
//! declared localizations, in step with the catalogues.

use crate::i18n::{catalogue_languages, load_all_catalogues, LANGUAGE_LOADER};
use i18n_embed::LanguageLoader;
use std::collections::HashMap;

/// Fields that never vary by language: paths, icon name, and the
/// autostart behaviour the packages rely on.
const STATIC_FIELDS: &str = "\
Exec=starla-tray
Icon=starla
Categories=System;Monitor;Network;
StartupNotify=false
X-GNOME-Autostart-enabled=true
";

/// Render the desktop entry, English keys first and one localized key
/// per additional catalogue.
///
/// Output does not depend on the locale this runs under: each field is
/// read from a loader pinned to the language it belongs to.
pub fn desktop_entry() -> String {
    load_all_catalogues();

    let english = LANGUAGE_LOADER.fallback_language().clone();
    let english_loader = LANGUAGE_LOADER.select_languages(&[&english]);
    let localized: HashMap<_, _> = catalogue_languages()
        .into_iter()
        .filter(|language| *language != english)
        // Cheap, but not free — one loader per language, reused across
        // the fields below.
        .map(|language| {
            let loader = LANGUAGE_LOADER.select_languages(&[&language]);
            (language, loader)
        })
        .collect();

    let mut entry = String::from(
        "# Generated by `starla-tray --print-desktop-entry`.\n# The visible fields come from \
         binaries/starla-tray/i18n/<lang>/starla-tray.ftl;\n# regenerate rather than editing this \
         file by hand.\n[Desktop Entry]\nType=Application\n",
    );

    for (key, message) in [
        ("Name", "desktop-name"),
        ("Comment", "desktop-comment"),
        ("Keywords", "desktop-keywords"),
    ] {
        let source = english_loader.get(message);
        entry.push_str(&format!("{}={}\n", key, source));

        let mut languages: Vec<_> = localized.keys().collect();
        languages.sort_by_key(ToString::to_string);
        for language in languages {
            let translated = localized[language].get(message);
            // Fluent falls back to English per message. An untranslated
            // field is better omitted than repeated — launchers already
            // fall back to the unsuffixed key.
            if translated != source {
                entry.push_str(&format!("{}[{}]={}\n", key, language, translated));
            }
        }
    }

    entry.push_str(STATIC_FIELDS);
    entry
}

#[cfg(test)]
mod tests {
    use super::*;

    const COMMITTED: &str = include_str!("../../../packaging/starla-tray.desktop");

    /// The packaged entry is a build artifact of the catalogues. When a
    /// translation lands and this fails, run
    /// `cargo run -p starla-tray -- --print-desktop-entry >
    /// packaging/starla-tray.desktop`.
    #[test]
    fn desktop_entry_matches_committed_file() {
        assert_eq!(
            desktop_entry(),
            COMMITTED,
            "packaging/starla-tray.desktop is stale"
        );
    }

    #[test]
    fn desktop_entry_localizes_every_catalogue() {
        let entry = desktop_entry();
        for language in catalogue_languages() {
            if language == *LANGUAGE_LOADER.fallback_language() {
                continue;
            }
            assert!(
                entry.contains(&format!("Comment[{}]=", language)),
                "{} has a catalogue but no localized Comment",
                language
            );
        }
    }

    /// macOS decides which languages an app claims to support from
    /// `CFBundleLocalizations`; a language missing there is a language
    /// the system will not offer even though the tray can render it.
    #[test]
    fn bundle_declares_every_catalogue() {
        const INFO_PLIST: &str = include_str!("../../../packaging/Info.plist");

        for language in catalogue_languages() {
            assert!(
                INFO_PLIST.contains(&format!("<string>{}</string>", language)),
                "packaging/Info.plist does not list {} in CFBundleLocalizations",
                language
            );
        }
    }
}
