[package]
name = "starla-results"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Measurement result management and upload for the Starla RIPE Atlas software probe"
repository.workspace = true
readme = "README.md"

[dependencies]
starla-common = { path = "../starla-common", version = "0.6.1" }
starla-metrics = { path = "../starla-metrics", version = "0.6.1" }
tokio = { workspace = true }
tokio-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
flate2 = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
