name: macOS

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
      - 'README.md'
      - '.github/dependabot.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22

      - name: Build packages
        run: |
          nix build .#default
          nix build .#starla-tray

      - name: Run tests
        run: |
          nix develop -c cargo test --workspace
