name: macOS

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Build packages
        run: |
          nix build .#default
          nix build .#starla-tray

      - name: Run tests
        run: |
          nix develop -c cargo test --workspace --all-features
